### ISSUE TITLE
Could the opencivicdata methods on the ScrapedCandidate model be devolved to the processed-data app

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-scraped-data#5]
Then this app would not require OCD as a dependency at all and could live as a free-standing module within our stack

**Comment by gordonje** [comment]
I believe the answer is "yes".

There are only two modules that import from `opencivicdata`:
1. [getsamplejson.py](https://github.com/california-civic-data-coalition/django-calaccess-scraped-data/blob/4f46f084f1d386242d1a0b3d15d145ae48457a77/example/toolbox/management/commands/getsamplejson.py) was a management command I wrote to spit out some example json for the elections OCDEP. It should probably move back under the processed data app. Though, it may have outlived its utility.
2. [candidates.py](https://github.com/california-civic-data-coalition/django-calaccess-scraped-data/blob/4f46f084f1d386242d1a0b3d15d145ae48457a77/calaccess_scraped/models/candidates/candidates.py) (under models) has couple of methods: `.get_or_create_post()` and `. get_or_create_person()`. These methods were written and added to the base management command in processed data app. Just checked and there are no calls anywhere to these model methods.
